# ==================================================
# GPIO CORE
# ==================================================
CONFIG_GPIO=y

# ==================================================
# UART / LOGGING
# ==================================================
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_PRINTK=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PRINTK=y

# Apagar shell por ahora
CONFIG_SHELL=n

# ==================================================
# BLUETOOTH CORE
# ==================================================
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y

# Nombre base por defecto
CONFIG_BT_DEVICE_NAME="Joya"

# Habilitar la capacidad de cambiar el nombre dinámicamente
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_NAME_MAX=32

# For debug
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=36      
# 45 ms - apple pide >= 15 ms, < 2 s (unidades de 1.25 ms)
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=72      
# 90 ms - apple pide <= 2 segundos
CONFIG_BT_PERIPHERAL_PREF_LATENCY=4       
# apple pide <= 30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=600     
# 6 s - apple pide entre 6 y 18 segundos (unidades de 10 ms)


CONFIG_BT_DEBUG_LOG=n

# ==================================================
# FOR FLASH STORAGE
# ==================================================
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y

CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

CONFIG_MPU_ALLOW_FLASH_WRITE=y