#ifndef AAP_COMM_H
#define AAP_COMM_H

enum {
    INIT_JOYA_COMMAND = 0x01,
    COMMAND_ROUTINE = 0x02,
    COMMAND_END_ROUTINE = 0x03,
    COMMAND_EMERGENCY = 0x04,
    END_JOYA_COMMAND = 0x05,

    INIT_APP_COMMAND = 0x10,
    COMMAND_STOP_EMERGENCY = 0x11,
    COMMAND_ACK_EMERGENCY = 0x12,
    COMMAND_FOLLOW_ME = 0x13,
    END_APP_COMMAND = 0x14,
};

#endif